<?php

namespace App\Web\Traits;

use Illuminate\Database\Eloquent\Model;

trait ResourceHasServersCluster
{
    public static function getUrl(string $name = 'index', array $parameters = [], bool $isAbsolute = true, ?string $panel = null, ?Model $tenant = null): string
    {
        if (! isset($parameters['server'])) {
            $parameters['server'] = request()->route('server') ?? 0;
        }

        return parent::getUrl($name, $parameters, $isAbsolute, $panel, $tenant); // TODO: Change the autogenerated stub
    }
}
