echo "load:$(uptime | awk -F'load average:' '{print $2}' | awk -F, '{print $1}' | tr -d ' ')"
echo "memory_total:$(free -k | awk 'NR==2{print $2}')"
echo "memory_used:$(free -k | awk 'NR==2{print $3}')"
echo "memory_free:$(free -k | awk 'NR==2{print $7}')"
echo "disk_total:$(df -BM / | awk 'NR==2{print $2}' | sed 's/M//')"
echo "disk_used:$(df -BM / | awk 'NR==2{print $3}' | sed 's/M//')"
echo "disk_free:$(df -BM / | awk 'NR==2{print $4}' | sed 's/M//')"
echo "cpu_cores:$(nproc 2>/dev/null || echo '')"
echo "cpu_physical_cores:$(lscpu -p=Socket,Core 2>/dev/null | grep -v '^#' | sort -u | wc -l)"
echo "swap_total:$(free -k | awk 'NR==3{print $2}')"
echo "swap_used:$(free -k | awk 'NR==3{print $3}')"
echo "swap_free:$(free -k | awk 'NR==3{print $4}')"
echo "swap_used_percent:$(free | awk 'NR==3{ if ($2>0) printf "%.2f", ($3/$2)*100; else print 0 }')"
echo "uptime_seconds:$(awk '{print $1}' /proc/uptime 2>/dev/null || echo '')"
echo "reboot_required:$([ -f /var/run/reboot-required ] && echo 1 || echo 0)"
echo "oom_kill_count:$(awk '/^oom_kill / {print $2; exit}' /proc/vmstat 2>/dev/null || echo 0)"
echo "cpu_usage_and_steal:$(LC_ALL=C top -bn1 2>/dev/null | awk '/^%?Cpu\(s\)/{ for(i=1;i<=NF;i++){ if($i ~ /us,/){us=$(i-1)}; if($i ~ /st/){st=$(i-1)} } printf "%s|%s", us, st }')"
