<?php

namespace App\Web\Clusters;

use Filament\Clusters\Cluster;
use Illuminate\Database\Eloquent\Model;

class Servers extends Cluster
{
    protected static ?string $slug = 'servers/view/{server}';

    protected static bool $shouldRegisterNavigation = false;

    public static function getUrl(array $parameters = [], bool $isAbsolute = true, ?string $panel = null, ?Model $tenant = null): string
    {
        $parameters['server'] = request()->route('server') ?? 0;

        return parent::getUrl($parameters, $isAbsolute, $panel, $tenant); // TODO: Change the autogenerated stub
    }
}
