[supervisord]
nodaemon=false
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:horizon]
user=root
autostart=true
autorestart=true
command=/usr/bin/php /var/www/html/artisan horizon
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/horizon.log
stopwaitsecs=3600
