name: Docker

on:
  push:
    branches:
      - 1.x
      - 2.x

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build . \
            -f docker/Dockerfile \
            -t vitodeploy/vito:${{ github.head_ref || github.ref_name }} \
            --build-arg="RELEASE=0" \
            --platform linux/amd64,linux/arm64 \
            --no-cache \
            --push
