name: release test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    name: Release test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create sqlite database
        run: touch storage/database-test.sqlite

      - name: Set up the .env file
        run: touch .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Generate API Docs
        run: php artisan scribe:generate

