name: tests

on:
  push:
    branches:
      - main
      - 1.x
      - 2.x
      - 3.x
      - 4.x
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.4 ]
        node-version: [ "22.x" ]
        database: [ sqlite, mysql, mariadb ]

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_DATABASE: vito_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      mariadb:
        image: mariadb:11
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
          MARIADB_DATABASE: vito_test
        ports:
          - 3307:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    name: tests (${{ matrix.database }})

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create sqlite database
        if: matrix.database == 'sqlite'
        run: touch storage/database-test.sqlite

      - name: Set up the .env file
        run: touch .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install NPM Dependencies
        run: npm install --force

      - name: Build assets
        run: npm run build

      - name: Run test suite
        env:
          DB_CONNECTION: ${{ matrix.database }}
          DB_DATABASE: ${{ matrix.database == 'sqlite' && 'database-test.sqlite' || 'vito_test' }}
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ matrix.database == 'mariadb' && '3307' || '3306' }}
          DB_USERNAME: root
          DB_PASSWORD: ""
        run: php artisan test --parallel
