name: Sync forked repository

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM (UTC), adjust as needed
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Sync main branch
        run: gh repo sync MelTheDev/vito -b main

      # Optional: Sync other branches
      - name: Sync additional branches
        run: |
          BRANCHES=("1.x" "main")  # Add your branch names here
          for branch in "${BRANCHES[@]}"; do
            gh repo sync MelTheDev/vito -b "$branch"
          done
